### ISSUE TITLE
Huggingface hub problem.

### ISSUE THREAD

**Issue by SiddharthGuptaPyDev** [FireRedTeam/FireRedTTS#24]
I'm getting this error when I try to run the FireRedTTS using the code given in the README.md (I think this problem is related to huggingface-hub version, so can you please include the huggingface-hub version also in the requirement,txt used to run it?) -
```
Traceback (most recent call last):
File "/teamspace/studios/this studio/FireRedTTS/test.py", line 3, in <module>
from fireredtts.fireredtts import FireRedTTS
File "/teamspace/studios/this studio/FireRedTTS/fireredtts/fireredtts.py", line 4, in <module>
from fireredtts.modules.gpt.gpt import GPT
File "/teamspace/studios/this studio/FireRedTTS/fireredtts/modules/__init__.py", line 5, in <module>
from fireredtts.modules.flow import get_flow_frontend, Melspectrogram Extractor
File "/teamspace/studios/this studio/FireRedTTS/fireredtts/modules/flow/__init__.py", line 4, in <module>
from fireredtts.modules.flow.decoder import ConditionalCFM, ConditionalDecoder
File "/teamspace/studios/this studio/FireRedTTS/fireredtts/modules/flow/decoder.py", line 7, in <module>
from diffusers.models.activations import get_activation
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.18/site-packages/diffusers/__init__.py", line 5, in <module>
from .utils import (
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.18/site-packages/diffusers/utils/__init__.py", line 38, in <module>
from .dynamic_modules_utils import get_class_from_dynamic_module
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.18/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
from huggingface hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface hub (/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

**Comment by liuhui881125** [comment]
https://github.com/easydiffusion/easydiffusion/issues/1851

**Comment by SiddharthGuptaPyDev** [comment]
> [easydiffusion/easydiffusion#1851](https://github.com/easydiffusion/easydiffusion/issues/1851)

Thank you so much for giving me the link! Still better than most of the Indian repos where you won't get any response even after 10 years! 👍
